# Exercise: Python Numerics
* The exercises below are intended to give us more familiarity with Python numerics
* For guidance, use the notes, the Python __`help()`__ function, or the online documentation

## First things first–import the numpy package

In [1]:
import numpy as np

## Create a vector of ten zeros

In [4]:
v = np.random.randint(0,1,size=10)
v

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Create a vector of size ten with nine zeros and a '1' in the fifth position

In [5]:
v = np.random.randint(0,1,size=9)
v[4] = 1
v

array([0, 0, 0, 0, 1, 0, 0, 0, 0])

## Create a vector with values ranging from 10 to 49

In [7]:
v = np.arange(10, 50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Reverse the previous vector

In [9]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [20]:
m = np.arange(0,9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Find the indices of the non-zero elements of the following array:

In [18]:
v = [1, 2, 0, 0, 4, 0]

In [19]:
np.nonzero(v)

(array([0, 1, 4]),)

## Create a 5x5 identity matrix

In [21]:
m = np.eye(5)
m

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## Create a 3x3x3 array with random values

In [22]:
m = np.random.random((3, 3, 3))
m

array([[[ 0.19791815,  0.3151708 ,  0.79620514],
        [ 0.15760193,  0.72007876,  0.52747031],
        [ 0.62079688,  0.81584381,  0.49962917]],

       [[ 0.50508752,  0.92111664,  0.97198467],
        [ 0.27514316,  0.8919504 ,  0.78082156],
        [ 0.96318286,  0.54389698,  0.50168157]],

       [[ 0.97205187,  0.21575962,  0.63395959],
        [ 0.78327459,  0.76471997,  0.29003238],
        [ 0.38329946,  0.26968756,  0.59919607]]])

## Find the minimum and maximum values generated in the previous step

In [25]:
min_value = m.min()
print(min_value)
max_value = m.max()
print(max_value)

0.157601925755
0.97205186577


## Create a vector with 30 random values and find its mean

In [28]:
v = np.random.random(30)
v.mean()

0.558159838930402

## Create a 5x5 2d array with 1's around the edges and 0's in the middle

In [31]:
m = np.ones((5, 5))
m[1:-1,1:-1] = 0
print(m)

[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


## Try to predict the outcome of each of the following cells before running them.

In [32]:
0 * np.nan

nan

In [33]:
np.nan == np.nan

False

In [34]:
np.inf > np.nan

False

In [35]:
np.nan - np.nan

nan

In [36]:
0.3 == 3 * 0.1

False

In [37]:
np.array(0) // np.array(0)

/Users/kpremnath/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [38]:
np.array(0) // np.array(0.)

nan

In [39]:
np.array(0) / np.array(0)

/Users/kpremnath/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [40]:
np.array(0) / np.array(0.)

/Users/kpremnath/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

## Find the integer part of the following array using four different methods:

In [41]:
a = np.random.uniform(0, 10, 10)
print(a)

[ 1.70074089  8.51271838  1.8656484   4.20108995  6.235879    8.08080655
  7.45045512  8.52697255  7.36445796  6.3458251 ]


In [42]:
print(np.floor(a))

[ 1.  8.  1.  4.  6.  8.  7.  8.  7.  6.]


In [44]:
print(np.ceil(a)

[ 2.  9.  2.  5.  7.  9.  8.  9.  8.  7.]


In [45]:
np.trunc(a)

array([ 1.,  8.,  1.,  4.,  6.,  8.,  7.,  8.,  7.,  6.])

In [46]:
a.astype(int)

array([1, 8, 1, 4, 6, 8, 7, 8, 7, 6])

## Create a vector of 10 values from 0 to 1, both included

In [47]:
v = np.linspace(0,1,10)
print(v)

[ 0.          0.11111111  0.22222222  0.33333333  0.44444444  0.55555556
  0.66666667  0.77777778  0.88888889  1.        ]


## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [48]:
v = np.linspace(0, 1, 12)[1:-1]
print(v)

[ 0.09090909  0.18181818  0.27272727  0.36363636  0.45454545  0.54545455
  0.63636364  0.72727273  0.81818182  0.90909091]


## Subtract the mean of each row of the following matrix

In [49]:
m = np.random.rand(3, 3)
print(m)

[[ 0.66227094  0.39179647  0.94885492]
 [ 0.98384916  0.88738253  0.43600357]
 [ 0.19050663  0.44814258  0.0522778 ]]


In [50]:
m - m.mean(axis=1, keepdims=True)

array([[-0.00536983, -0.27584431,  0.28121414],
       [ 0.21477074,  0.11830411, -0.33307485],
       [-0.03980237,  0.21783357, -0.1780312 ]])

## Add 1,000,000 numbers together using Numpy vectorized operations

In [55]:
v = np.random.random(1000000)
np.sum(v)

499823.50152931875

## Create a 4x4 array of the first 16 powers of 3

In [56]:
a = np.arange(16).reshape((4,4))
3 ** a

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]])