## Import the numpy package

In [2]:
import numpy as np

## Create a vector of ten zeros

In [5]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Create a vector of size ten with nine zeros and a '1' in the fifth position

In [4]:
v = np.zeros(10)
v[4] = 1
print(v)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Create a vector with values ranging from 10 to 49

In [7]:
v = np.arange(10, 50)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Reverse the previous vector

In [8]:
v[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
m = np.arange(0,9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Find the indices of the non-zero elements of the following array:

In [13]:
v = [1, 2, 0, 0, 4, 0] # Given

In [14]:
np.nonzero(v)

(array([0, 1, 4]),)

## Create a 5x5 identity matrix

In [15]:
m = np.eye(5)
print(m)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Create a 3x3x3 array with random values

In [17]:
a = np.random.random((3, 3, 3))
print(a)

[[[0.18816195 0.10104997 0.53529592]
  [0.19577721 0.16285803 0.15912437]
  [0.90689474 0.0589899  0.47471442]]

 [[0.34722156 0.66072441 0.2650533 ]
  [0.70504891 0.59889149 0.7219431 ]
  [0.62859646 0.54900881 0.41806756]]

 [[0.95035598 0.75089211 0.65221559]
  [0.59422487 0.23476825 0.81715304]
  [0.24886623 0.92048501 0.57021664]]]


## Find the minimum and maximum values generated in the previous step

In [18]:
print(a.min())
print(a.max())

0.058989902115416104
0.9503559771270539


## Create a vector with 30 random values and find its mean

In [19]:
v = np.random.random(30)
print(v.mean())

0.4878474155981818


## Create a 5x5 2d array with 1's around the edges and 0's in the middle

In [21]:
a = np.ones((5, 5))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Try to predict the outcome of each of the following cells before running them.

In [22]:
0 * np.nan

nan

In [23]:
np.nan == np.nan

False

In [24]:
np.inf > np.nan

False

In [25]:
np.nan - np.nan

nan

In [26]:
0.3 == 3 * 0.1

False

In [3]:
np.array(0) // np.array(0)

/Users/dws/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [4]:
np.array(0) // np.array(0.)

/Users/dws/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in floor_divide
  """Entry point for launching an IPython kernel.


nan

In [5]:
np.array(0) / np.array(0)

/Users/dws/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [6]:
np.array(0) / np.array(0.)

/Users/dws/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

## Find the integer part of the following array using four different methods:

In [31]:
a = np.random.uniform(0, 10, 10)
print(a)

[4.07654319 1.35603252 7.54013996 8.30223689 9.87028622 5.28781576
 0.88853703 9.75292204 0.54243978 8.15387407]


In [32]:
print(np.floor(a))

[4. 1. 7. 8. 9. 5. 0. 9. 0. 8.]


In [33]:
print(np.ceil(a) - 1)

[4. 1. 7. 8. 9. 5. 0. 9. 0. 8.]


In [34]:
a.astype(int)

array([4, 1, 7, 8, 9, 5, 0, 9, 0, 8])

In [35]:
np.trunc(a)

array([4., 1., 7., 8., 9., 5., 0., 9., 0., 8.])

## Create a vector of 10 values from 0 to 1, both included

In [38]:
v = np.linspace(0,1,10)
print(v)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [39]:
v = np.linspace(0, 1, 12)[1:-1]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## Subtract the mean of each row of the following matrix

In [41]:
m = np.random.rand(3, 3)
print(m)

[[0.24237077 0.21901068 0.69953911]
 [0.79131496 0.82160017 0.48639873]
 [0.93165467 0.62558216 0.68875018]]


In [44]:
m - m.mean(axis=1, keepdims=True)

array([[-0.14460275, -0.16796284,  0.31256559],
       [ 0.09154368,  0.12182888, -0.21337256],
       [ 0.18299233, -0.12308017, -0.05991216]])

## Add 1,000,000 numbers together using Numpy vectorized operations

In [7]:
v = np.random.random(1_000_000)
np.sum(v)

500254.93743324385

## Create a 4x4 array of the first 16 powers of 3

In [50]:
a = np.arange(16).reshape((4,4))
3 ** a

array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]])